# Generated by Django 5.1.7 on 2025-03-29 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='item_images/')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('date_lost_or_found', models.DateTimeField()),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Returned', 'Returned')], default='Lost', max_length=10)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
            ],
        ),
    ]
