# Generated by Django 5.1.7 on 2025-09-16 22:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_image_recognition_result'),
        ('locations', '0004_location_description_location_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.TextField(max_length=100)),
                ('date_reported', models.DateTimeField(blank=True, editable=False)),
                ('date_lost_or_found', models.DateTimeField()),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found'), ('Returned', 'Returned')], default='Lost', max_length=10)),
                ('image_recognition_result', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical item',
                'verbose_name_plural': 'historical items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('can_soft_delete_item', 'Can soft delete item')]},
        ),
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_deleted'], name='items_item_is_dele_79eaf1_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='items_item_status_819478_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-date_reported'], name='items_item_date_re_9b4bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['date_lost_or_found'], name='items_item_date_lo_71ff76_idx'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.location'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='reported_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
