# Generated by Django 5.1.7 on 2025-09-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_historicalitem_alter_item_options_item_deleted_at_and_more"),
        ("items", "0004_remove_item_image_recognition_result"),
    ]

    operations = []
