# Generated by Django 5.1.7 on 2025-03-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=42.3709),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=-72.516),
            preserve_default=False,
        ),
    ]
